docs: update `go get` link in README
So `go get` will still sometimes throw an error:

scron/util/crontab.go:52:15: undefined: cron.Parse

Even though cron.Parse *is* defined in robfig/cron@v1.2.0 !!!
If this happens you need to manually `cd` into the checked out repo and
run `go build`, which works fine...